Updated config syntax.
srcery-colors/srcery-gui pull request #10
Opened 2021-04-22 05:11 UTC by wos-dv

2021-04-22 09:27 UTC, roosta commented
Hi, thanks for your contribution!

In the rofi readme there are trailing whitespace that should be addressed. The commits "Improved readme.md." should be squashed. The commit messages should be in present tense. (Improve readme.md), and remove trailing period in commit messages.

I'm unable to test awesome theme easily, hopefully there are someone in the community able to test it. Maybe add a screenshot somewhere?

2021-04-22 09:28 UTC, roosta requested changes

2021-04-22 09:28 UTC, roosta commented on rofi/README.md
> +
trailing whitespace, indentation issues

2021-04-22 12:57 UTC, wos-dv commented
Reorganized the committs. Added a screenshot for AwesomeWM. I would fix the indentation too, but I don't know what is wrong with it. Can you elaborate?

2021-04-22 13:16 UTC, roosta commented
![image](https://user-images.githubusercontent.com/4509009/115720439-5f4c2f80-a37d-11eb-91b1-f5dbd1cd5c1e.png)
Just some trailing whitespace, dunno why the indentation was wrong previously, thought maybe you used a tab char or something, but seems to be ok now. Love the new log, much cleaner :+1:

2021-04-22 17:09 UTC, wos-dv commented
Removed the spaces.

2021-04-23 16:59 UTC, roosta approved these changes

2021-04-24 07:55 UTC, merged

2021-04-24 07:55 UTC, MindTooth commented
Thank you for the contrib. 👍🏻